### ISSUE TITLE
Enhancement Request: Support identification of merged cells

### ISSUE THREAD

**Issue by abhishekdattagit** [masaccio/numbers-parser#1]
Thanks for this excellent little package.
Would it be possible to support a cell API that supports querying for the "merged" attribute?

**Comment by masaccio** [comment]
Sure I can certainly take a look at that. Thinking about the API I'd probably need to introduce a Cell object and give it range/merged parameters which will be a different API. I need to look into the data to see how merges are encoded so might not be a quick fix.

Are you thinking horizontal as well as vertical merges? If you have an example spreadsheet you can share that will help in testing.

Jon

**Comment by masaccio** [comment]
@abhishekdattagit I've added a method cells() which returns Cell objects for the type of cell in the table. This includes MergedCell objects which represent cells that have been merged. I've found where Numbers stores the list of merged cells but I haven't figured out how to associate a list of merges with a particular table.

**Comment by abhishekdattagit** [comment]
Thanks Jon. I am going to try the method and report back.
The spreadsheet I am using just now has some privileged information, but I can create one with merged cells like it, if you are still interested in an example.

**Comment by masaccio** [comment]
No need to share a document then. I've just pushed some additional changes to GitHub, but not to PyPI yet and these include some new methods. Basically the MergedCell objects (the removed 'empty' cells when a merge happens) have a merge_range which is the range of cells that cover the whole merge. The 'source' of the merge (the cell that remains) has an is_merged property that is True/False on whether the cell is merged.

tests/test_merges.py  has loads of examples of the API and I'll refactor/document stuff this weekend

Would be great to hear if it works for you as the extracting of the merge ranges was the most complex reverse-engineering of the file format I've done to date and I am a little worried it might still be fragile.

**Comment by abhishekdattagit** [comment]
Brilliant. This works for the cases I tried out as expected. Thanks Jon!
