### ISSUE TITLE
Request for numbers-parser information

### ISSUE THREAD

**Issue by rbpaul** [masaccio/numbers-parser#13]
I wouldn’t say this is an issue, but a request for information.  

1) I have one.numbers file with multiple sheets and one table per sheet.  Is it possible to use numbers-parser to replace a table (or sheet) in this one.numbers file with a table (or sheet) from another.numbers file?  It is not intuitive to me how this might be done.

2) Since numbers can open a .csv file, is it possible to use numbers-parser to open a .csv file and save it as a .numbers file?

**Comment by semireg** [comment]
Unfortunately, parser means read-only. Modifying a Numbers file will likely be an order of magnitude more challenging - and from my perspective it's a miracle we have parsing capabilities. 🥳 Thank you to the contributors for what we have so far!

**Comment by masaccio** [comment]
I'm afraid writing Numbers files is beyond the scope of what I think is possible in Python. What I think you could do though is read in the table you want to insert, save as CSV and then use AppleScript to add that to the other spreadsheet. But then if you're not manipulating the data AppleScript would be able to do all this.

Applescript is a horrible language though the more you write it, the less you hate it. I've pasted in something I use to categorise transactions after I've imported data from a bank account. Maybe it'll give you some ideas but I expect you'll start as I did with lots of google on how to write AppleScript!

A more modern approach is likely to be a combination of JavaScript and Automator but I've never tried.

Jon

``` Applescript
on get_transactions_lookup(reference_sheet_name)
	set transactions_lookup to {}
	tell application "Numbers"
		tell document 1
			set current_sheet to name of active sheet
			tell sheet "Transactions" to tell table reference_sheet_name
				repeat with row_count from 2 to row count
					set keyword_value to value of cell 1 of row row_count
					set category_value to value of cell 2 of row row_count
					if keyword_value ≠ missing value then
						set lookup_item to {keyword:keyword_value, category:category_value}
						copy lookup_item to the end of the transactions_lookup
					end if
				end repeat
			end tell
		end tell
	end tell
	return transactions_lookup
end get_transactions_lookup

on lookup_transaction_category(lookup_table, transaction_text)
	repeat with lookup_value in lookup_table
		ignoring case
			if transaction_text contains keyword of lookup_value then
				return category of lookup_value
			end if
		end ignoring
	end repeat
	return "Other"
end lookup_transaction_category

set transactions_lookup to get_transactions_lookup("Transactions")
tell application "Numbers"
	if not (exists document 1) then error number -128
	tell document 1 to repeat with the_sheet in sheets
		if name of the_sheet ≠ "Transactions" and name of the_sheet ≠ "Summary" then
			tell the_sheet to tell table 1
				repeat with row_count from 1 to row count
					if value of cell 1 of row row_count = "Date" then
						exit repeat
					end if
				end repeat
				set start_row to row_count + 1
				repeat with row_count from start_row to row count
					set transaction_text to value of cell 2 of row row_count
					set category to my lookup_transaction_category(transactions_lookup, transaction_text)
					set last_cell_num to count of row
					set the value of last cell of row row_count to category
					--set the value of cell last_cell_num of row row_count to category
				end repeat
			end tell
		end if
	end repeat
end tell
```

**Comment by semireg** [comment]
AppleScript hurts the way "chewing on tinfoil while screeching fingernails on a chalkboard" hurts... 😄 

I wonder if you could use Excel as an intermediary to programmatically organize the sheets, then just use the implicit "conversion" of Excel to Numbers by virtue of opening them. I'm assuming there is much better r/w excel libraries in existence that can generate the required formats.

**Comment by rbpaul** [comment]
Thanks you for your prompt and helpful response.  I will close this issue/request for information.  Once I have learned to automate data input into a .numbers file, I will return here to learn how to retrieve it.

**Comment by masaccio** [comment]
@rbpaul I've since added support for writing Numbers files. You'll need to clone the repo to get the latest version as it's still in development, but happy for feedback if you're still interested.
