### ISSUE TITLE
AttributeError: 'Formula' object has no attribute '_table_id'

### ISSUE THREAD

**Issue by reviewher** [masaccio/numbers-parser#14]
[Test file, download and rename with `.numbers` extension](https://github.com/masaccio/numbers-parser/files/8150892/XLOOKUP.Examples.xls) then run `cat-numbers --formula`

**Comment by masaccio** [comment]
Fixed in 2.3.5 (added XLOOKUP). There's still some decode of storage buffers that I don't quite understand for formula keys so let me know if there are other breakages.
