### ISSUE TITLE
merge ranges

### ISSUE THREAD

**Issue by SheetJSDev** [masaccio/numbers-parser#18]
File under "undocumented black magic": [merge-test.zip](https://github.com/masaccio/numbers-parser/files/8345862/merge-test.zip)

It's ok if you don't think this is valid -- Numbers 11.2 won't write this field, but it parses correctly all the way back to Numbers 3.5.

**Comment by masaccio** [comment]
Reads OK for me with latest numbers-parser and no errors. There are calls to check for merged cells if that's what you mean?

**Comment by SheetJSDev** [comment]
B3:D3 are merged in the file:

<img width="640" alt="ss" src="https://user-images.githubusercontent.com/6070939/160092304-90b8dbda-2f17-411f-8acb-ee75c56feaf8.png">

However the library isn't picking it up:

```python
>>> from numbers_parser import Document, Cell, MergedCell
>>> doc = Document("merge-test.numbers")
>>> sheets = doc.sheets()
>>> table = sheets[0].tables()[0]
>>> table.cell("B3").merge_range
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TextCell' object has no attribute 'merge_range'
>>> table.cell("B3").is_merged
False
```

There's a part in the DataStore message:

```proto
message DataStore {
  // ...
  optional .TSP.Reference merge_region_map = 13;
  // ...
}

message MergeRegionMapArchive {
  repeated .TST.CellRange cell_range = 1;
}

message CellRange {
  required .TST.CellID origin = 1;
  required .TST.TableSize size = 2;
}

message TableSize {
  required fixed32 packedData = 1;
  optional uint32 num_columns = 2;
  optional uint32 num_rows = 3;
}

message CellID {
  required fixed32 packedData = 1;
  optional .TSCE.CellCoordinateArchive expanded_coord = 2;
}
```

The packing is 16-bit little-endian integers for row, col in a fixed32 (type=5) wire field (https://github.com/SheetJS/sheetjs/blob/master/modules/83_numbers.ts#L916 is how the merge part is constructed -- the message type is 6144 and can live in the same file as the TableModelArchive)

ATM It's unclear how conflicts between the region map and the CalculationEngine stuff should be handled.

**Comment by masaccio** [comment]
Getting away from needing the CalculationEngine data would not be a bad thing (would just be formulas if I changed the merge stuff). Thanks for all the detail.

**Comment by masaccio** [comment]
But your original assertion of "It's ok if you don't think this is valid" is where I am at in that Numbers doesn't write this when saving though obviously it does support it in the files you write. Numbers strips this away when reading and replaces it with all the CalculationEngine stuff.

I'll leave this issue open for now but I don't currently plan a fix.

**Comment by masaccio** [comment]
@SheetJSDev just returning to this and 3.0.0 will include save support. Everything is committed to the main branch. I haven't pushed it to PyPI yet as the write support has had very little testing and I know that not all values are being reflected in Numbers when a file is opened.

However your test case does now read so hopefully helpful for your own testing.

**Comment by SheetJSDev** [comment]
Awesome!  As you expand write support, please test against our parser (you can drag-drop files into the box in https://oss.sheetjs.com/ -- it parses in the web browser) and report any issues you may encounter (https://github.com/SheetJS/sheetjs/issues).

If you are finding issues with incorrect numeric values, https://github.com/masaccio/numbers-parser/blob/main/src/numbers_parser/model.py#L638 should be revisited.  It looks like you are writing an IEEE754 double (unless some recent python version changed how `d` is interpreted), but the value in the v5 storage is actually a decimal128.  [JS engines do not provide the primitive, so SheetJS has to implement the logic directly](https://github.com/SheetJS/sheetjs/blob/master/modules/83_numbers.ts#L53-L69)

**Comment by masaccio** [comment]
Curious how you deal with decimal128 in SheetJS - do you treat numbers as having 128-bit precision? Just discovering that one of my tests happens to road badly ( 132.0*0.1 = 13.200000000000001) and now mulling over whether to switch internal representation of real numbers to decimal128. It doesn't fix that specific example as anyone rounding to a float will see the fraction.

Feels like there's a reason my life an an engineer has avoided floating point arithmetic.

**Comment by SheetJSDev** [comment]
Excel and other software generally use doubles.  Given the overall vision of translating data between file formats, t is a reasonable compromise for SheetJS to use doubles and translate to/from decimal128.  https://github.com/SheetJS/sheetjs/blob/master/modules/83_numbers.ts#L53-L69 is a decent starting point.

As for Numbers itself, it seems to use doubles in the calculation engine:

Rename the attached file with a .numbers extension: [754.zip](https://github.com/masaccio/numbers-parser/files/8642417/754.zip)

<img width="207" alt="" src="https://user-images.githubusercontent.com/6070939/167181445-4b677d11-c50b-4e35-9fee-19311f121ce5.png">

The maximum integer that can safely be represented in an IEEE754 double is

```python
>>> 2**53-1
9007199254740991
```

The loss of data (compare A4 to A6) suggests doubles in the calculation engine.

**Comment by masaccio** [comment]
Will close this now since merge_map is implemented. I've adapted your scheme for decoding/encoding decimal128. I've included a credit in README.md but not referred to your Apache license (numbers-parser is MIT). If you'd like me to do more please let me know. See here: https://github.com/masaccio/numbers-parser/blob/71aa86cf906cf9fd2e9a45768072e83bbe168d19/src/numbers_parser/model.py#L1025-L1050
