### ISSUE TITLE
Double header rows in pandas

### ISSUE THREAD

**Issue by meeffe** [masaccio/numbers-parser#23]
Hello, 

These code:

```
import pandas as pd

doc = Document("simple.numbers")
sheets = doc.sheets()
tables = sheets[0].tables()
data = tables[0].rows(values_only=True)
df = pd.DataFrame(data, columns=["A", "B", "C"])

```

...doubles the header rows. I mean when I have a standalone header row in .numbers file and pass this .numbers file to pandas it treats the header row as a normal row too and as a result I am getting pandas dataframe where the first row contains column headings (which is correct) and below I get standalone row which contains same values as above. 

Any solution for that besides deleting the header rows inside .numbers file?

**Comment by masaccio** [comment]
Ah right. You need something like this then:

``` python
data = tables[0].rows(values_only=True)
df = pd.DataFrame(data[1:], columns=data[0])
```

The `rows` method will return data and headers so using the first element of that list for the column names is what you need.

**Comment by meeffe** [comment]
@masaccio thanks. Working as expected now.
