### ISSUE TITLE
performance against large files

### ISSUE THREAD

**Issue by SheetJSDev** [masaccio/numbers-parser#34]
test file https://github.com/SheetJS/nodeno/blob/master/large_strings.numbers

From SheetJS, you can get a sense for expected performance by cloning the repo https://github.com/SheetJS/nodeno and either:

A) setting up https://bun.sh/ and running `time bun read.js large_strings.numbers`

B) setting up https://nodejs.org/en/ and running `time node read.mjs large_strings.numbers`

It takes ~3 seconds on a 2018 i9 MBP either way.

Using the PyPI version (2.3.12) with `time cat-numbers -b large_strings.numbers` on Python 3.9.13, it runs close to 57 seconds.

Is there some library option or missing setup to improve performance?

**Comment by masaccio** [comment]
Do you know if you have protobuf with native code pure Python installed? I think you might need to compile it from source — instructions in the readme on my main branch.  My recollection is that gives around 10-20x performance uplift. 

If it’s not that then I will need to look. Certainly when I last benchmarked, time was mostly in file IO and protobuf and I already aggressively cache everything possible.

**Comment by masaccio** [comment]
https://github.com/masaccio/numbers-parser/blob/main/README.md#protobuf-updates

**Comment by masaccio** [comment]
```pip install --upgrade --only-binary macosx_10_9_universal2 protobuf```

didn't install anything useful for me (as in not faster) and there was just one shared object in the Python wheel which looks very suspicious. And still slow as you say.

I need to do some digging into what protobuf is shipping and compare to my self-built version. I'd rather not ship my own protobuf.

**Comment by masaccio** [comment]
Profiler picked out a missing cache for large string tables which didn't show up with smaller ones. I still can't see how to get a faster protobuf to cleanly install.

Anyway, v2.3.13 cats the file in 4s on my M1.

**Comment by SheetJSDev** [comment]
Thanks for digging into this!  It's literally an order of magnitude improvement.  On the same machine it's ~6 seconds.
