### ISSUE TITLE
Duration formatting

### ISSUE THREAD

**Issue by SheetJSDev** [masaccio/numbers-parser#37]
https://github.com/SheetJS/test_files/blob/master/duration_112/duration_112.numbers test file.

There are a few places where the duration formatting details are stored.  For modern sheets, they are in the format table (`.TST.DataStore` field 22)

There are three types of duration format and 21 manually specified field sets (stored as start and end granularity) as well as an "automatic" option.

**Comment by masaccio** [comment]
Are you OK me adapting your implementation as-needed (we use different OSS licenses - hence me asking)?

https://github.com/SheetJS/sheetjs/blob/df0e7b5f255140acf874668b7c0779c04b20997d/modules/83_numbers.ts#L372

**Comment by masaccio** [comment]
Should be complete in v3.1.0

**Comment by masaccio** [comment]
DurationCells have a formatted_value property which is the string value

**Comment by SheetJSDev** [comment]
The data from the API looks right:

```python
>>> from numbers_parser import Document
>>> doc = Document("duration_112.numbers")
>>> sheets = doc.sheets
>>> [sheet.tables[0].rows()[20][6].formatted_value for sheet in sheets]
['1:01', '1h 1m', '1 hour 1 minute', '1:01', '1h 1m', '1 hour 1 minute']
```

Can `cat-numbers` show the formatted value (it can be opt-in with a command line flag)?

**Comment by masaccio** [comment]
Sure `--formatting` added for durations in v3.2.0. When formatting of dates as they appear in Numbers is supported, the same option will enable that.

**Comment by masaccio** [comment]
Which turned out to be straightforward and is in v3.3.0. See the note in the README about am/pm resulting from `datetime.strftime`. Also the test file is saved with text values for the check column which are in UK locale.

**Comment by SheetJSDev** [comment]
en-US hours are missing.  Remove `.zip` from the linked file and test: 

[en-US-times.numbers.zip](https://github.com/masaccio/numbers-parser/files/9543240/en-US-times.numbers.zip)

```
% cat-numbers --formatting  -b en-US-times.numbers 
Value,Value 0,Value 1,Value 2,Value 3,Value 4,Value 5
12:00 AM,,12 AM,12:00 AM,12:00:00 AM,H:00,H:00:00
1:01 AM,,1 AM,1:01 AM,1:01:01 AM,H:01,H:01:01
9:09 AM,,9 AM,9:09 AM,9:09:09 AM,H:09,H:09:09
10:10 AM,,10 AM,10:10 AM,10:10:10 AM,H:10,H:10:10
11:11 AM,,11 AM,11:11 AM,11:11:11 AM,H:11,H:11:11
12:12 PM,,12 PM,12:12 PM,12:12:12 PM,H:12,H:12:12
11:23 PM,,11 PM,11:23 PM,11:23:23 PM,H:23,H:23:23
```

That `H` should be hours in a 24-hour system (range 0-23), which would be `%-H` for `strftime`

Linked CSV is the expected output: [en-US-times.numbers.csv](https://github.com/masaccio/numbers-parser/files/9543241/en-US-times.numbers.csv)

Note that 24 hours with padding cannot be created by default in en-US Numbers.  When you select a cell using hours with padding, the time format options are:

<img width="187" alt="numberstimeformat" src="https://user-images.githubusercontent.com/6070939/189543159-01132ae5-d862-4274-9e7d-d92d0c4670df.png">

That last option is the current cell format, displayed when selecting a cell that doesn't use one of the built-in formats.  The antepenultimate option in the screenshot is `H:MM` and the penultimate option is `H:MM:SS`

**Comment by masaccio** [comment]
Ack - also done in latest patch release

**Comment by SheetJSDev** [comment]
Looks good!
