### ISSUE TITLE
Text after a break line in the same cell cannot be extracted

### ISSUE THREAD

**Issue by traceymeng** [masaccio/numbers-parser#4]
Steps to reproduce.
1. Create a new Numbers file.
2. Type "part 1" in a cell.  Tap Option+Return (in MacBook) to create a new line in the same cell.  Type a phrase such as "part 2" in the newly created line of the same cell.
3. Save the Numbers file and close the file.
4. Use numbers-parser to read the content of this cell.  The word of "part 2" which is after the new line won't be recognized.  Only the texts before the new line ("part 1") are picked up
5. Note, if there are more new lines in the same cell, the value of the cell becomes None, i.e., "part 1" cannot be extracted.

Or unzip and open the attached parts.numbers.zip file
[parts.numbers.zip](https://github.com/masaccio/numbers-parser/files/7707381/parts.numbers.zip)
.

**Comment by masaccio** [comment]
Which method(s) are you using to return the data? It looks OK to me:

```
% cat-numbers -b /Users/jon/Downloads/parts.numbers 
,,,,,,
,Part 1 

Part 2
,,,,,
,,,,,,
```

This was with version 2.1.1 of numbers-parser and I used `table.cell(row, col)` to get the data

**Comment by masaccio** [comment]
@traceymeng I've added https://github.com/masaccio/numbers-parser/blob/master/tests/test_issues.py as a test so let me know if this is what you're doing.

I'll close the issue as done in a couple of weeks if there's no more activity.

Thanks for raising.

**Comment by traceymeng** [comment]
Thanks, Jon.

I did not get time to test it.  I'll let you know if I still have issues.

Best Regards,

Tracey
