### ISSUE TITLE
Saving negative numbers

### ISSUE THREAD

**Issue by ChrisKing4** [masaccio/numbers-parser#49]
I created a spread sheet in Numbers that contained both positive and negative numbers. In a python script using the numbers-parser, I loaded that document and saved it back out to a new file without modifying it.
When I opened the new document in numbers, all the negative numbers have been clamped to zero.

**Comment by masaccio** [comment]
I can’t spot anything eyeballing the code just now so will take a proper look next weekend and publish an update. If you have a moment to attach a failing example that would help just in case it turns out to be an edge case.

**Comment by masaccio** [comment]
Fixed in v3.9.6.
