### ISSUE TITLE
AttributeError: 'Table' object has no attribute 'data', and how to convert to a pandas dataframe

### ISSUE THREAD

**Issue by osheanlee** [masaccio/numbers-parser#5]
Hi! I'm currently following the README document, and whenever I run `data = tables[0].data`, it's returning the error:

```
AttributeError: 'Table' object has no attribute 'data'
```

My `.numbers` file currently contains two (2) tables -- Table 1 has only 2 rows filled, while Table 2 is empty. I tried different workaround to fix it (i.e. modifying my `.numbers` file from my iOS device and all), but it's still returning said error.

Also, would anybody here know how to convert `.numbers` to a pandas dataframe? That's my end goal actually. Thanks!

**Comment by semireg** [comment]
I think there’s an error in the README. It should be data().

**Comment by osheanlee** [comment]
@semireg also tried it too, and not working also.

**Comment by masaccio** [comment]
@osheanlee since the return value of data() is a list of lists, you should be able to pass it straight to pandas like this:

```
from numbers_parser import Document
import pandas as pd

doc = Document("tests/data/test-1.numbers")
sheets = doc.sheets()
tables = sheets[0].tables()
data = tables[0].rows(values_only=True)
df = pd.DataFrame(data, columns=["A", "B", "C"])
print(df)
```

I've pushed changes to the Readme (not on PyPI yet) for the correct method to extract all data, which is `rows()`

**Comment by masaccio** [comment]
I've also added the pandas example to the README. Holler if you spot any issues.
