### ISSUE TITLE
Doesn't work if there are more than 65536 rows

### ISSUE THREAD

**Issue by safinaskar** [masaccio/numbers-parser#50]
`numbers-parser` seem not to work if an input `.numbers` document has more than 65536 rows.

Someone gave to me `.numbers` document. I have PC with Linux installed, so I have no Numbers. I installed `numbers-parser` and converted the document to CSV using `cat-numbers`. But resulting CSV documents has 65536 normal rows and then I see `,,,,,,,,,,,,,,,,` (or `None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None` in `--formatting` mode). And I think that original document has additional data.

Unfortunately, I don't want to provide original document via public Github issue, because it contains confidential data.

Also, I'm not sure this is `numbers-parser`'s problem, it is possible that they created broken document in the first place

**Comment by masaccio** [comment]
There shouldn't be a problem with that many rows; Numbers supports documents up to 1M rows.

I just tried an empty document with >180k rows adding some text at the end and `cat-numbers` did what I expected in dumping all rows. Something you can try to see if the document is corrupted is using [SheetJS](https://sheetjs.com/demo/). It stores data in-browser so you're not transferring the document to their server.

Failing that if you trust me with the document, I am happy to share a dropbox URL with you.

This also works as expected:

``` python
from numbers_parser import Document
doc = Document()
sheets = doc.sheets
tables = sheets[0].tables
table = tables[0]
x = 0
for row in range(0, 100000):
    for col in range(0, 4):
        table.write(row, col, x)
        x += 1
doc.save("large.numbers")
```

``` shell
% cat-numbers large.numbers | wc -l
  100000
```

**Comment by masaccio** [comment]
There are a couple of suggestions here: https://askubuntu.com/questions/408306/is-there-a-way-to-read-osx-numbers-files

LibreOffice doesn't advertise `.numbers` support, but random Internet person claims it works. Creating a free iCloud account, even if it's just a trial is a good idea as you'll be able to upload and then download as Excel. It's also a sure-fire way to see if the file is corrupted. If iCloud can't load it, then it's borked.

**Comment by masaccio** [comment]
Yup when I use strings in that example above, I get 2^10 strings dumped and then nothing. File creation actually works, so it's 'just' in reading. Will fix and if you don't mind testing the fix, that would be great.

**Comment by safinaskar** [comment]
Yes, I will test

**Comment by safinaskar** [comment]
Yes, now it works
