### ISSUE TITLE
node type COLON_TRACT_NODE is unsupported

### ISSUE THREAD

**Issue by barnacle-carnival** [masaccio/numbers-parser#54]
Using Numbers version 13.1 (7037.0.101)

I can reproduce this error by opening up a new document selecting a few cells in a column, and creating it as a SUM().  Numbers works fine, but I get errors like:

/usr/local/lib/python3.11/site-packages/numbers_parser/formula.py:252: UnsupportedWarning: Table 1@[3,1]: node type COLON_TRACT_NODE is unsupported
/usr/local/lib/python3.11/site-packages/numbers_parser/formula.py:102: UnsupportedWarning: Table 1@[3,1]: stack too small for SUM

The "stack too small for" error also affects MIN() and MAX() and probably any function which accepts a range.

The actual function code produced is:  "SUM(B2:B3)"
However, numbers_parser returns only "SUM()" (note the lack of args) from cell.formula

**Comment by masaccio** [comment]
Looks like cell references changed a lot in 13.x. Will take a few days to come back to this.

**Comment by masaccio** [comment]
@SheetJSDev FYI on new cell reference types in function ASTs. [`_NumbersModel. tract_to_row_col_ref`](https://github.com/masaccio/numbers-parser/blob/main/src/numbers_parser/model.py#L466) should be pretty clear.

**Comment by barnacle-carnival** [comment]
Version 3.10.4 runs without any errors and my SUM functions now have values in them!  Fixed!

Thanks!
