### ISSUE TITLE
Cell styles are lost when saving the document

### ISSUE THREAD

**Issue by burakgok** [masaccio/numbers-parser#56]
When I open and save a document without doing any modification; the background color, column width and text alignment of cells are lost (defaulted).

**numbers-parser:** 3.11.0
**Numbers:** 13.1 (7037.0.101)
**Input file:** Test.numbers in [Files.zip][1]
**Output file:** Test2.numbers in [Files.zip][1]

[1]: https://github.com/masaccio/numbers-parser/files/11995188/Files.zip

**Comment by masaccio** [comment]
Styles should be saved now. There's support for editing styles coming, but this is not documented yet as it's not working.
