### ISSUE TITLE
Unable to write border styles

### ISSUE THREAD

**Issue by KhanWhale** [masaccio/numbers-parser#64]
Hi, thank you for this package! It's really helpful. I am trying to write out a numbers file, and part of this involves formatting specific cells with specific borders. I dug through the source code and found methods that seem to enable this, but they do not seem to be accessible after importing.

**Comment by masaccio** [comment]
Borders are not supported just yet. Expect something soon though as I am close to figuring out how to write these. I have one remaining bug that can cause Numbers can hang.

**Comment by KhanWhale** [comment]
Sounds good–let me know if there's anything I can do to assist!

**Comment by masaccio** [comment]
This is public in v4.3.0. There's some limited docs to the new APIs and [a more complete example here](https://github.com/masaccio/numbers-calendar/blob/main/src/numbers_calendar/_numbers_calendar.py) that creates a calendar.

**Comment by KhanWhale** [comment]
Thank you for resolving! One more question–is text wrapping supported at this time?

**Comment by masaccio** [comment]
It isn't. Are you looking to set the style of a cell as wrapped/not wrapped? There's a straightforward boolean flag in the cell properties that could easily be implemented, but asking what the use case is.

**Comment by KhanWhale** [comment]
Yup, that's exactly correct, I am trying to wrap text in the cell (set text wrapping = true)

**Comment by masaccio** [comment]
Text wrap defaults true like in new Numbers documents. I'll publish an update shortly that allows you to check this when reading documents and turn it off. But you should see text wrapped in new documents.
