### ISSUE TITLE
TypeError: 'ItemsList' object is not callable

### ISSUE THREAD

**Issue by traceymeng** [masaccio/numbers-parser#65]
**Describe the bug**
After I updated to the latest build of 4.4.2, I got following error:
sheets = doc.sheets()
TypeError: 'ItemsList' object is not callable

**To Reproduce**
Try to parse the attached numbers file with following code:
    doc = Document(args.filePath)
    sheets = doc.sheets()
    

**Expected behavior**

**Attachments**

[TestFile.numbers.zip](https://github.com/masaccio/numbers-parser/files/12444258/TestFile.numbers.zip)

**Additional information**
Please provide the version number (output of `cat-numbers --version`
4.4.2

I'm using Python 3.10.11

**Comment by masaccio** [comment]
You should have been seeing a deprecation warning for some time about `sheets()` which has been a property rather than a method since v3. I removed the method entirely in v4. You need to use `doc.sheets` and then `sheet.tables`.
