### ISSUE TITLE
Cells containing bullets or list cannot be parsed.  None is returned as the value of cells which containing butlers or list.

### ISSUE THREAD

**Issue by traceymeng** [masaccio/numbers-parser#7]
If cells contain bullets or list, none is return as the cell's value.

Please unzip and read the text content in the attached file. 
[Test1.numbers.zip](https://github.com/masaccio/numbers-parser/files/7832374/Test1.numbers.zip)

**Comment by masaccio** [comment]
This is definitely a limitation of the supported encodings. I can see from a dump of your spreadsheet that the data is stored as a text string but also has metadata indicating the paragraph indexes. Apple store the unformatted text plus annotations indicating how it should be formatted in that cell. I will probably add a new cell type that derives from `TextCell` with paragraphs optionally as a list.

Differentiating between a bulleted list and an enumerated list is possible but does venture off into supporting styles which feels like quite the rabbit hole so I will almost certainly pass on that.

Since the table storage doesn't look overly complex, I will do that at least this weekend. Thanks for the issue report.

**Comment by masaccio** [comment]
@traceymeng If you are OK using a git checkout of the latest checkin, can you take a look at the new cell type `ParagraphTextCell` which will return plain text like this:

``` python
value = table.cell(0, 1).value
print(value)
```

and individual bullets like this:

``` python
bullets = table.cell(0, 1).paragraph
print(bullets[0])
```

If this works for you I will document and publish a v2.2. It's not possible at the moment to distinguish between different types of lists; only the text is extracted.

**Comment by traceymeng** [comment]
Hi Jon,

Thank you so much for your quick response.  The typical use case is a
single format of either bullets or a list in all cells of a column.  I
don't think anyone will use the mixed type in the same column.   The
purpose that I put mixed types in a single column is just for your
testing.

The problem I have is that I don't know if a cell contains bullets.  For my
current use case, I just need to retrieve all contents in a cell as a whole
paragraph when I call table.cell(0, 1).value instead of None value. It
would be nice if the contents maintains bullets or list, but skip bullet
symbol (keep the line return) is also acceptable. I don't need to separate
each bullet line, which may not be the job of the parser.

Best Regards,

Tracey

**Comment by masaccio** [comment]
I've added an is_bulleted property so the behaviour is now:

- `table.cell(0, 1).is_bulleted` returns `True` or `False` depending upon whether the cell has bullets/lists or not
- `table.cell(0, 1).value` always returns the cell contents. In the case of bulleted lists this will be the text only, separated by newlines
- `table.cell(0, 1).bullets` returns a list of the individual bullets if the cell has them, or `None` otherwise

It would be a lot harder to insert (say) a `'*'` character to represent the bullets as that woulds require detection of styles and insertion of extra characters.

A couple of new tests might help:

https://github.com/masaccio/numbers-parser/blob/master/tests/test_bullets.py
https://github.com/masaccio/numbers-parser/blob/master/tests/test_issues.py

` test_issue_7` in the second test file is the code that reads your spreadsheet (I've added it to my tests which I hope is fine with you).

**Comment by masaccio** [comment]
There is also a full example in the README now. I think this all works for what you have described so let me know.

**Comment by traceymeng** [comment]
Thanks, Jon.

This works for my current use case.

Regards,

Tracey

**Comment by masaccio** [comment]
Great, thanks Tracey. If you pip update the package, you'll get v2.2 which has these new features.

**Comment by traceymeng** [comment]
Hi jon,

Looks like this latest fix breaks the previous fix which fixed the multiple
lines in the same cell.  Would you please try the attached file?   I get
None value for cell 2A ( Sing in with an account ...) which contains some
empty lines at the end.  The minimum request is to retrieve any text
including line returns.  If you may get the empty lines, please add them,
otherwise, trim them.

Thank you for your time.

Best Regards,

Tracey

**Comment by masaccio** [comment]
Cell A2 is empty in the spreadsheet you attached and there's no text with "sign in" I can find. Sorry to throw back to you but do yo have an updated spreadsheet you can share?

**Comment by traceymeng** [comment]
Hi Jon,

cell = table.cell(j, col_steps)

How do I check the cell type from above?  After the above line of code, the
cell type is already declared.  How do I check if this cell is a TextCell
or a cell contains paragraphs or bullets?  If the cell is a TextCell, then
I cannot call cell.paraph due to the error of "AttributeError: 'TextCell'
object has no attribute 'paragraph' ".

Best Regards,

Tracey

**Comment by traceymeng** [comment]
Hi Jon,

I have a question on how to check a cell type.

I checked your test files.  In your unit test, you only assert the data type you already know.  For example, you know that a cell contains bullets, so you assert .is_bullet is True.  However, in real situations, we do not know if a cell contains bullets, paragraph, or pure text.  So  after I call cell = table.cell(I,j), I need to check what the cell type is.  If the cell is a bullet-type, I’ll do more actions. Would you please provide me examples to check the cell type of table.cell(I,j)?

Also, since we agree that you only extract texts, May we have some rules on handling formatted contents?  For example, replace all paragraph ending with a line separator; replace horizontal line separator with a new line; replace all bullets with a space; and etc.  basically, replace no text tokens with either space, line return or empty line.

These are my two cents.

Regards,

Tracey

**Comment by masaccio** [comment]
Sorry I ended up using a different name. Here's the code:

``` python
doc = Document("bullets.numbers")
sheets = doc.sheets()
tables = sheets[0].tables()
table = tables[0]
if not table.cell(0, 1).is_bulleted:
    print(table.cell(0, 1).value)
else:
    bullets = ["* " + s for s in table.cell(0, 1).bullets]
    print("".join(bullets))
```

The `is_bulleted` property will always exist but the `bullets` property only exists if `is_bulleted` returns `True`. I should probably have `bullets` return `None`.

Since the paragraphs are a list you can manipulate them using regular Python so the example above creates a string where there is a a bullet `*` character at the beginning of each line. Is that enough?

**Comment by traceymeng** [comment]
Thanks, Jon.

1. Just like to confirm that ‘.is_bulleted‘ property is not in the release of 2.2. 

2. In the example you provided, * is a know symbol.  Do you convert all types of bullet symbols to * internally?  If yes, this approach works, otherwise, it won’t work because I do not know what the bullet symbol is used by a user.  As a result, please convert any type of bullet or number list to a fixed symbol such as ‘-‘ or ‘*’.  I prefer ‘-‘.

3. I’m not clear about the approach you proposed for paragraph.  Do you mean that you will return a list type as a return of table.cell()?  In fact, may we make things simple by just return two types: Text cell and List cell.  If .is_list, I go through the list. 
The Text Cell type is also a single element list, so the list can handle all cases, but for the reason of backward compatibility, you may have to keep the TextCell type.  What do you think?

Regards,

Tracey

**Comment by masaccio** [comment]
Are you sure about v2.2. I tried this with an installed package:

``` python
from numbers_parser import Document

doc = Document("Test1.numbers")
sheets = doc.sheets()
tables = sheets[0].tables()
table = tables[0]
for x, row in enumerate(table.iter_rows()):
    for y, cell in enumerate(row):
        if cell.is_bulleted:
            print(f"[{x}, {y}]:")
            bullets = ["* " + s for s in cell.bullets]
            print("\t" + "\t".join(bullets))
        else:
            print(f"[{x}, {y}]:", cell.value)
```

and got this result:

```
% python3 example.py 
[0, 0]: None
[0, 1]: Steps
[1, 0]: None
[1, 1]:
	* Open http://www.mytest.com/music on Desktop. Click Radio on left penal
	* Take a screenshot including the bottom banner
[2, 0]: None
[2, 1]:
	* Click the bottom banner
	* See the generic Individual upsell
	* Take a screenshot
	* Dismiss the upsell
[3, 0]: None
[3, 1]:
	* Click Account on top menu bar
	* Select Upgrade to Family
	* See the Family upsell
	* Take a screenshot 
	* Dismiss the upsell
[4, 0]: None
[4, 1]:
	* Click Search field
	* Enter “drake”, press return key to search
	* Scroll down to Songs
	* Click a song to play
	* See the Song contextual upsell
	* Take a screenshot
	* Dismiss the upsell
[5, 0]: None
[5, 1]:
	* http://www.google.com
	* http://www.yahoo.com and http://www.cnn.com 
	* 
```

It's quite hard to extract whether the bullet is a `*` or a `-` or for that matter a numbered list. I can see the data but it would be a lot more work to do this as I would need to implement extraction of paragraph styles as Numbers stores the contents of numbered and bulleted lists as lists of text and then applies a style to each entry in the list which is then stored elsewhere.

The version I have installed is:

```
% cat-numbers --version
2.2.0
```

And the `numbers_parser/cell.py` is the same as my most recent checkin. Does the example make sense?

**Comment by traceymeng** [comment]
Hi Jon,

Thanks for the confirmation.   I cleaned my environment and things works fine now.  What offered in version 2.2 is good to me.  Thanks again.

Regards,

Tracey

**Comment by masaccio** [comment]
Great thanks - sorry I can't easily extract the type of bullet.

**Comment by masaccio** [comment]
@traceymeng 

Hi Tracey,

I've actually found it is more straightforward than I thought to extract the bullets. In doing so I 

```python
    assert table.cell(4, 2).bullets[0] == "star-bullet-1"
    assert table.cell(4, 2).bullets[2] == "dash-bullet"
    assert table.cell(3, 2).formatted_bullets[4] == "• bullet-5"
    assert table.cell(4, 2).formatted_bullets[0] == "★ star-bullet-1"
```

I've not pushed this to PyPI yet. It will be a v3.0 as the API is changing and I have also decided to remove the newline from the bullets as it's more consistent. I don't get know how to extract numbered lists (they are stored differently to bullets) but it is possible to extract the character as per the example above.

So I have reopened the issue and will keep you posted. 

Jon

**Comment by masaccio** [comment]
@traceymeng 

Hi Tracey,

I've actually found it is more straightforward than I thought to extract the bullets. In doing so I 

```python
    assert table.cell(4, 2).bullets[0] == "star-bullet-1"
    assert table.cell(4, 2).bullets[2] == "dash-bullet"
    assert table.cell(3, 2).formatted_bullets[4] == "• bullet-5"
    assert table.cell(4, 2).formatted_bullets[0] == "★ star-bullet-1"
```

I've not pushed this to PyPI yet. It will be a v3.0 as the API is changing and I have also decided to remove the newline from the bullets as it's more consistent. I don't get know how to extract numbered lists (they are stored differently to bullets) but it is possible to extract the character as per the example above.

So I have reopened the issue and will keep you posted. 

Jon

**Comment by masaccio** [comment]
v2.3.0 now includes the new `Cell.formatted_bullets` property. This places the appropriate bullet character(s) at the beginning of the string. It does not currently support numbering starting from a custom offset such as a list 10, 11, 12.
