### ISSUE TITLE
How to search for a specific text in a table?

### ISSUE THREAD

**Issue by coachrye** [masaccio/numbers-parser#70]
Hi, 

Is there a way to easily search for a specific text in a table? Or do I really need to use iter_rows or iter_cols?

Thanks!

**Comment by masaccio** [comment]
There's no search implemented. Using `sheet.tables[0].rows(values_only=True)` gets you a list of lists and is efficient as possible given how Numbers data is stored.

**Comment by coachrye** [comment]
Thanks for taking the time to respond, @masaccio ! Happy holidays to you! Cheers.
