### ISSUE TITLE
Support for Adding and Deleting Rows

### ISSUE THREAD

**Issue by AndrewClose** [masaccio/numbers-parser#72]
This is great! Thanks for creating this library!

Are there any plans to support adding and deleting rows?

Thanks!

**Comment by AndrewClose** [comment]
Excellent!  Thanks for your quick response Jon!  This should work.  Cheers!

**Comment by masaccio** [comment]
Closing this as v4.8.0 now has functions to do this: [`Table.add_row()`](https://masaccio.github.io/numbers-parser/api/document.html#numbers_parser.Table.add_row) and [`Table.delete_row()`](https://masaccio.github.io/numbers-parser/api/document.html#numbers_parser.Table.add_row). Both methods take a `start_row` and a number of rows. There are column methods to match them.
