### ISSUE TITLE
Can't set cell data format to Text

### ISSUE THREAD

**Issue by BreadMoirai** [masaccio/numbers-parser#83]
Not sure how to set a cell data format to Text

```py
table.set_cell_formatting(row, col, "text")
```

errors out with
```py
File "/Users/tonly/repo/venv/backupqa/lib/python3.9/site-packages/numbers_parser/document.py", line 1407, in set_cell_formatting
    self._set_cell_data_format(row, col, format_type, **kwargs)
  File "/Users/tonly/repo/venv/backupqa/lib/python3.9/site-packages/numbers_parser/document.py", line 1447, in _set_cell_data_format
    if type_name not in FORMATTING_ALLOWED_CELLS[format_type_name]:
KeyError: 'text'
```

**Comment by masaccio** [comment]
The valid formatting types are described in [the API docs](https://masaccio.github.io/numbers-parser/api/table.html#numbers_parser.Table.set_cell_formatting). 

If you write a python `str` to a cell using [Table.write](https://masaccio.github.io/numbers-parser/api/table.html#numbers_parser.Table.write), the cell format is automatically chosen to be a `TextCell`.

Maybe if you could explain the expected outcome you're looking for?

**Comment by masaccio** [comment]
Closing as this is expected to fail and v4.10.6 now throws a suitable exception for the invalid forma type.
