### ISSUE TITLE
"invalid IWA file Index/CalculationEngine.iwa"

### ISSUE THREAD

**Issue by reviewher** [masaccio/numbers-parser#9]
[Download and remove the `.xls` extension](https://github.com/masaccio/numbers-parser/files/7967996/Untitled.numbers.xls) -- sorry, github enforces extensions on attachments :(

Error message `Index/CalculationEngine.iwa: invalid IWA file Index/CalculationEngine.iwa`

[This is believed to be the contents of `Index/CalculationEngine.iwa` after de-framing and de-compressing](https://github.com/masaccio/numbers-parser/files/7967993/CalculationEngine.iwa.xls)

<details><summary><b>Suspected offsets for message starts</b> (click to show)</summary>

```
0
23662
24249
24431
24632
24813
24994
25177
25360
25542
25722
25859
26414
26595
26798
26980
27164
27347
27530
27713
27895
28034
28731
28914
29116
29300
29484
29668
29851
30035
30217
30356
30965
31574
32181
32363
32566
32747
32929
33112
33294
33476
33657
33794
34521
34704
34908
35092
35274
35457
35640
35824
36007
36146
36869
37634
37817
38020
38203
38386
38569
38751
38933
39116
39255
39658
40425
41241
41424
41627
41811
41995
42178
42362
42544
42728
42867
42892
45312
45527
46681
46723
46955
46977
47020
47064
47088
47439
47455
47476
47506
47522
48489
50086
51045
51578
51792
52942
52984
53216
53238
53282
53326
53350
53701
53717
53738
53768
53784
54751
56359
57369
58865
59082
60224
60266
60553
60575
60619
60663
60687
61038
61054
61075
61105
61121
62296
63930
64147
65298
65340
65569
65591
65635
65677
65701
66052
66068
66089
66119
66135
67123
68366
69354
70597
71585
72828
73041
74174
74216
74666
74688
74732
74776
74800
75151
75167
75188
75218
75234
76766
78102
78319
79470
79512
79880
79902
79946
79990
80014
80363
80379
80400
80430
80446
81886
82629
82843
83996
84038
84403
84425
84468
84510
84534
84885
84901
84922
84952
84968
86478
```

</details>

**Comment by masaccio** [comment]
So a quick hack is to comment out the assertion on  iwafile.py:109 but in a classic example of "engineers write lousy comments" I can't actually remember why I put the assertion in so I need to spend a bit more time on this. Thanks for the test though -- I'm sure the fix won't be overly hard.

**Comment by reviewher** [comment]
Looks good!
