### ISSUE TITLE
The rules of TSPRegistryMapping

### ISSUE THREAD

**Issue by cheng-deer** [masaccio/numbers-parser#92]
hi, I would like to ask you a few questions. For example, the src/umbers_parser/generated/mapping.py file here
TSPRegistryMapping = {
"1": "TN.DocumentArchive",
"2": "TN.SheetArchive",
...
}What logic is used to define it. How is the key generated here? I don't understand, please work hard to clarify my confusion. thank you

**Comment by masaccio** [comment]
It is auto-generated using `src/build/extract_mapping.py` by dumping an internal data structure of the Numbers application using the LLDB debugger. There is some background information [here](https://github.com/obriensp/iWorkFileFormat/blob/master/Docs/index.md). See also the Credits section of [this part of the readme](https://github.com/masaccio/numbers-parser/blob/main/docs/api/development.rst).

**Comment by cheng-deer** [comment]
Thank you very much for your answer. Best wishes
