### ISSUE TITLE
Can't Overwrite and then Save the document if the Collaboration is turned on. 

### ISSUE THREAD

**Issue by daddytigerflying** [masaccio/numbers-parser#94]
**Describe the bug**
A local `numbers` file can be overwritten and saved successfully.
```
from numbers_parser import Document
doc = Document('test.numbers')
sheet = doc.sheets[0]
table = sheet.tables[0]

table.write("A1", "test message")
doc.save('test.numbers')
```

But if this `numbers` file is collaborated, first it's no long a file. 
<img width="1324" alt="image" src="https://github.com/user-attachments/assets/272bff3d-4b86-4efe-846a-8fd1697c099c">

```
>>> from pathlib import Path
>>> Path('test.numbers').is_file()
False
```
And Error raised when overwrite and save. 
```
>>> from numbers_parser import Document
>>> doc = Document('test.numbers')
>>> sheet = doc.sheets[0]
>>> table = sheet.tables[0]

>>> table.write("A1", "test message")
>>> doc.save('test.numbers')

IsADirectoryError: [Errno 21] Is a directory: 'test.numbers'
```

**To Reproduce**
To create a Numbers document and turn on the `collaboration`.
![image](https://github.com/user-attachments/assets/7211e564-46c4-49f3-9cb9-2c3ab33909dd)

**Expected behavior**
Overwrite & Save fail and raise `IsADirectoryError`

**Comment by masaccio** [comment]
Are you looking to save the file as a directory? There is a flag in the [`Document.save()`](https://masaccio.github.io/numbers-parser/api/document.html#numbers_parser.Document.save) method that can force the creation of a folder format. I had expected that writing into a folder without `package=True` would raise a `FileFormatError`.

**Comment by daddytigerflying** [comment]
Ah, yes it works! Thanks for this awesome tool, which fully satisfies me who has been suffering to find proper tools to manipulate Numbers app. With this package utilized in my data work, all my team members will no longer need to manually maintain the Numbers file. Thanks again! 

Numbers app itself has no an elegant and complete script API sets (tried PyObjc, AppleScript or appscript). Hopefully we can leverage more features in this package!
