### ISSUE TITLE
parser document logic

### ISSUE THREAD

**Issue by cheng-deer** [masaccio/numbers-parser#95]
Hello, may I ask how the content in this document is associated with the proto file. For example, when parsing a table, how do you know if the base_data_store contains content data? Because there are no comments in the proto file here, and it is unclear about the internal structure documentation of the iwa file. Where can I learn about this knowledge?

**Comment by masaccio** [comment]
Only Apple has this information and it is proprietary to them. What information is encoded in this package is through lots of reverse engineering over many months. 

There is some background information [here](https://github.com/obriensp/iWorkFileFormat/blob/master/Docs/index.md). See also the Credits section of [this part of the readme](https://github.com/masaccio/numbers-parser/blob/main/docs/api/development.rst).

Another implementation is in SheetJS and that product’s OSS version has some [notes on the format](https://oss.sheetjs.com/notes/iwa/).
